version: 2
updates:
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: monthly
    allow:
      - dependency-type: production
    reviewers:
      - zombiezen
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - zombiezen
